name: build

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    tags:
    - 'v*'
  pull_request:
    branches:
    - 'main'

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub & GHCR
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Login to the Github Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to My Gitea Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.GITEA_SERVER }}
        username: ${{ secrets.GITEA_USERNAME }}
        password: ${{ secrets.GITEA_ACCESS_TOKEN }}

    - uses: docker/metadata-action@v5
      id: meta
      with:
        # list of Docker images to use as base name for tags
        images: |
          docker.io/${{ github.repository }}
          ghcr.io/${{ github.repository }}
          ${{ secrets.GITEA_SERVER }}/${{ secrets.GITEA_REPOSITORY }}
        flavor: |
          latest=auto
        # generate Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}          
          type=raw,value=latest
          
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
